export const kpiItems = [
  {
    id: 1,
    name: "Адель ВХ",
    plan: 5000,
    fact: 1,
    percent: 99,
    type: "entrance",
    kpi: "KPI1",
  },
  {
    id: 2,
    name: "Урбан ВХ",
    plan: 14,
    fact: 1,
    percent: 95,
    type: "interior",
    kpi: "KPI2",
  },
  {
    id: 3,
    name: "Доканто серый бархат ВХ",
    plan: 300,
    fact: 24,
    percent: 86,
    type: "interior",
    kpi: "KPI3",
  },
  {
    id: 4,
    name: "Сити зеркало Метал-Метал",
    plan: 30,
    fact: 14,
    percent: 75,
    type: "entrance",
    kpi: "KPI2",
  },
  {
    id: 5,
    name: "Лу ВХ",
    plan: 45,
    fact: 24,
    percent: 69,
    type: "interior",
    kpi: "KPI1",
  },
  {
    id: 6,
    name: "Сицилия ВХ",
    plan: 70,
    fact: 24,
    percent: 58,
    type: "interior",
    kpi: "KPI3",
  },
  {
    id: 7,
    name: "Гладкая ВХ",
    plan: 14,
    fact: 12,
    percent: 45,
    type: "interior",
    kpi: "KPI2",
  },
  {
    id: 8,
    name: "Американская решетка ВХ",
    plan: 80,
    fact: 24,
    percent: 37,
    type: "interior",
    kpi: "KPI3",
  },
  {
    id: 9,
    name: "Барокко",
    plan: 180,
    fact: 24,
    percent: 26,
    type: "entrance",
    kpi: "KPI1",
  },
  {
    id: 10,
    name: "Лиственница ВХ",
    plan: 32,
    fact: 25,
    percent: 20,
    type: "interior",
    kpi: "KPI3",
  },
  {
    id: 11,
    name: "Лиственница ВХ",
    plan: 25,
    fact: 24,
    percent: 18,
    type: "interior",
    kpi: "KPI2",
  },
  {
    id: 12,
    name: "Лиственница ВХ",
    plan: 35,
    fact: 24,
    percent: 15,
    type: "interior",
    kpi: "KPI3",
  },
  {
    id: 13,
    name: "Лиственница ВХ",
    plan: 91,
    fact: 24,
    percent: 12,
    type: "entrance",
    kpi: "KPI1",
  },
  {
    id: 14,
    name: "Лиственница ВХ",
    plan: 170,
    fact: 24,
    percent: 5,
    type: "entrance",
    kpi: "KPI2",
  },
];

export const kpiSelectOptions = [
  { value: "", label: "Все KPI" },
  { value: "KPI1", label: "KPI № 1" },
  { value: "KPI2", label: "KPI № 2" },
  { value: "KPI3", label: "KPI № 3" },
];
