export const kpiItems = [
  {
    id: 1,
    name: "Адель ВХ",
    plan: 5000,
    fact: 1,
    percent: 99,
    type: "Входные двери",
    kpi: "KPI № 1",
    material: "Итальянский орех",
    img: "door1.png",
  },
  {
    id: 2,
    name: "Урбан ВХ",
    plan: 14,
    fact: 1,
    percent: 95,
    type: "Межкомнатные двери",
    kpi: "KPI № 2",
    material: "Итальянский орех",
    img: "door2.png",
  },
  {
    id: 3,
    name: "Доканто серый бархат ВХ",
    plan: 300,
    fact: 24,
    percent: 86,
    type: "Межкомнатные двери",
    kpi: "KPI № 3",
    material: "Итальянский орех",
    img: "door3.png",
  },
  {
    id: 4,
    name: "Сити зеркало Метал-Метал",
    plan: 30,
    fact: 14,
    percent: 75,
    type: "Входные двери",
    kpi: "KPI № 2",
    material: "Итальянский орех",
    img: "door4.png",
  },
  {
    id: 5,
    name: "Лу ВХ",
    plan: 45,
    fact: 24,
    percent: 69,
    type: "Межкомнатные двери",
    kpi: "KPI № 1",
    material: "Итальянский орех",
    img: "door5.png",
  },
  {
    id: 6,
    name: "Сицилия ВХ",
    plan: 70,
    fact: 24,
    percent: 58,
    type: "Межкомнатные двери",
    kpi: "KPI № 3",
    material: "Итальянский орех",
    img: "door6.png",
  },
  {
    id: 7,
    name: "Гладкая ВХ",
    plan: 14,
    fact: 12,
    percent: 45,
    type: "Межкомнатные двери",
    kpi: "KPI № 2",
    material: "Итальянский орех",
    img: "door7.png",
  },
  {
    id: 8,
    name: "Американская решетка ВХ",
    plan: 80,
    fact: 24,
    percent: 37,
    type: "Межкомнатные двери",
    kpi: "KPI № 3",
    material: "Итальянский орех",
    img: "door1.png",
  },
  {
    id: 9,
    name: "Барокко",
    plan: 180,
    fact: 24,
    percent: 26,
    type: "Входные двери",
    kpi: "KPI № 1",
    material: "Итальянский орех",
    img: "door2.png",
  },
  {
    id: 10,
    name: "Лиственница ВХ",
    plan: 32,
    fact: 25,
    percent: 20,
    type: "Межкомнатные двери",
    kpi: "KPI № 3",
    material: "Итальянский орех",
    img: "door3.png",
  },
  {
    id: 11,
    name: "Лиственница ВХ",
    plan: 25,
    fact: 24,
    percent: 18,
    type: "Межкомнатные двери",
    kpi: "KPI № 2",
    material: "Итальянский орех",
    img: "door4.png",
  },
  {
    id: 12,
    name: "Лиственница ВХ",
    plan: 35,
    fact: 24,
    percent: 15,
    type: "Межкомнатные двери",
    kpi: "KPI № 3",
    material: "Итальянский орех",
    img: "door5.png",
  },
  {
    id: 13,
    name: "Лиственница ВХ",
    plan: 91,
    fact: 24,
    percent: 12,
    type: "Входные двери",
    kpi: "KPI № 1",
    material: "Итальянский орех",
    img: "door6.png",
  },
  {
    id: 14,
    name: "Лиственница ВХ",
    plan: 170,
    fact: 24,
    percent: 5,
    type: "Входные двери",
    kpi: "KPI № 2",
    material: "Итальянский орех",
    img: "door7.png",
  },
];

export const kpiSelectOptions = [
  { value: "", label: "Все KPI" },
  { value: "KPI № 1", label: "KPI № 1" },
  { value: "KPI № 2", label: "KPI № 2" },
  { value: "KPI № 3", label: "KPI № 3" },
];
export const constTasks = [
  {
    id: "001",
    name: "Позвонить в отдел маркетинга по поводу визиток",
    // mm.dd.yyyy
    dateCreate: "09.12.2021 12:34",
    dateEnd: "09.12.2021 12:34",
    active: true,
  },
  {
    id: "002",
    name: "Сформирован (1)",
    dateCreate: "09.12.2021 12:34",
    dateEnd: "09.12.2021 12:34",
    active: false,
  },
];
